version: '3.8'
services:
  mariadb:
    build: ./DB
    container_name: mariadb_container  # 컨테이너 이름 설정
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # 루트 계정 비밀번호
      MYSQL_DATABASE: my_database  # 생성할 기본 데이터베이스
      MYSQL_USER: my_user  # 사용자 계정
      MYSQL_PASSWORD: my_password  # 사용자 계정 비밀번호
    ports:
      - "3306:3306"  # 로컬 호스트의 3306 포트와 컨테이너의 3306 포트 연결
    volumes:
      - mariadb_data:/var/lib/mysql  # MariaDB 데이터 영구 저장

volumes:
  mariadb_data:  # 데이터 저장을 위한 볼륨
