# Python 3.9 기반의 슬림 이미지를 사용합니다.
FROM python:3.9-slim

# 작업 디렉토리 생성 및 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사 로컬에 있는 파일 복사
COPY . .

# 컨테이너 시작 시 uvicorn으로 FastAPI 앱 실행 (main.py의 app 객체를 실행)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
